export const idlFactory = ({ IDL }) => {
  const LoginResponse = IDL.Record({
    'msg' : IDL.Text,
    'timeStamp' : IDL.Int,
    'responseStatus' : IDL.Text,
  });
  const LoginAttempt = IDL.Record({
    'loginHash' : IDL.Text,
    'loginClient' : IDL.Text,
    'loginIp' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Environment__1 = IDL.Record({
    'id' : IDL.Int,
    'workerId' : IDL.Int,
    'dateCreated' : IDL.Int,
    'name' : IDL.Text,
    'creatorId' : IDL.Int,
    'lastUpdated' : IDL.Int,
    'description' : IDL.Text,
    'projectId' : IDL.Int,
    'projectRepoBranch' : IDL.Text,
    'environmentType' : IDL.Text,
    'deploymentNetwork' : IDL.Text,
    'identityId' : IDL.Int,
  });
  const Deployment = IDL.Record({
    'id' : IDL.Int,
    'status' : IDL.Text,
    'projectRepo' : IDL.Text,
    'executeStartTime' : IDL.Int,
    'dateCreated' : IDL.Int,
    'creatorId' : IDL.Int,
    'lastUpdated' : IDL.Int,
    'executeFinishTime' : IDL.Int,
    'projectId' : IDL.Int,
    'environmentId' : IDL.Int,
    'projectRepoBranch' : IDL.Text,
    'identityId' : IDL.Int,
    'deploymentNotes' : IDL.Text,
  });
  const CreateDeploymentResponse = IDL.Record({
    'msg' : IDL.Text,
    'timeStamp' : IDL.Int,
    'deploymentObject' : Deployment,
    'responseStatus' : IDL.Text,
  });
  const Job = IDL.Record({
    'id' : IDL.Int,
    'status' : IDL.Text,
    'workerId' : IDL.Int,
    'dateCreated' : IDL.Int,
    'jobType' : IDL.Text,
    'lastUpdated' : IDL.Int,
    'environmentId' : IDL.Int,
    'refType' : IDL.Text,
    'refId' : IDL.Int,
  });
  const CreateIiEnableJobResponse = IDL.Record({
    'msg' : IDL.Text,
    'timeStamp' : IDL.Int,
    'jobObject' : Job,
    'responseStatus' : IDL.Text,
  });
  const CanisterStatusResponse = IDL.Record({
    'msg' : IDL.Text,
    'timeStamp' : IDL.Int,
    'responseStatus' : IDL.Text,
    'uptime' : IDL.Int,
    'everLoggedIn' : IDL.Text,
  });
  const Canister = IDL.Record({
    'id' : IDL.Int,
    'canisterName' : IDL.Text,
    'canisterType' : IDL.Text,
    'canisterNetwork' : IDL.Text,
    'dateCreated' : IDL.Int,
    'name' : IDL.Text,
    'dfxJson' : IDL.Text,
    'creatorId' : IDL.Int,
    'lastUpdated' : IDL.Int,
    'description' : IDL.Text,
    'lastDeploymentId' : IDL.Int,
    'projectId' : IDL.Int,
    'environmentId' : IDL.Int,
    'category' : IDL.Text,
    'identityId' : IDL.Int,
    'canisterId' : IDL.Text,
  });
  const CompleteCanisterResponse = IDL.Record({
    'msg' : IDL.Text,
    'canisterObject' : Canister,
    'lastDeploymentObject' : Deployment,
    'timeStamp' : IDL.Int,
    'responseStatus' : IDL.Text,
  });
  const CompleteDashboardStats = IDL.Record({
    'msg' : IDL.Text,
    'environmentsCount' : IDL.Nat,
    'timeStamp' : IDL.Int,
    'projectsCount' : IDL.Nat,
    'projectsActive' : IDL.Nat,
    'responseStatus' : IDL.Text,
    'eventsCountLast30' : IDL.Nat,
    'environmentsActive' : IDL.Nat,
    'deploymentsCountLastDay' : IDL.Nat,
    'deploymentsCount' : IDL.Nat,
    'eventsCount' : IDL.Nat,
  });
  const Event__1 = IDL.Record({
    'id' : IDL.Int,
    'localTime' : IDL.Int,
    'workerId' : IDL.Int,
    'deploymentId' : IDL.Int,
    'dateCreated' : IDL.Int,
    'creatorId' : IDL.Int,
    'jobId' : IDL.Int,
    'lastUpdated' : IDL.Int,
    'mainRefType' : IDL.Text,
    'projectId' : IDL.Int,
    'environmentId' : IDL.Int,
    'eventText' : IDL.Text,
    'eventType' : IDL.Text,
  });
  const Environment = IDL.Record({
    'id' : IDL.Int,
    'workerId' : IDL.Int,
    'dateCreated' : IDL.Int,
    'name' : IDL.Text,
    'creatorId' : IDL.Int,
    'lastUpdated' : IDL.Int,
    'description' : IDL.Text,
    'projectId' : IDL.Int,
    'projectRepoBranch' : IDL.Text,
    'environmentType' : IDL.Text,
    'deploymentNetwork' : IDL.Text,
    'identityId' : IDL.Int,
  });
  const Worker__1 = IDL.Record({
    'id' : IDL.Int,
    'status' : IDL.Text,
    'privateIp' : IDL.Text,
    'dateCreated' : IDL.Int,
    'iiEnabled' : IDL.Text,
    'name' : IDL.Text,
    'creatorId' : IDL.Int,
    'ttydHttpsEnabled' : IDL.Text,
    'lastUpdated' : IDL.Int,
    'uniqueId' : IDL.Text,
    'description' : IDL.Text,
    'lastTouch' : IDL.Int,
    'lastDeploymentId' : IDL.Int,
    'dnsName' : IDL.Text,
    'publicIp' : IDL.Text,
    'category' : IDL.Text,
    'ttydHttpsCount' : IDL.Int,
    'dfxReplicaType' : IDL.Text,
  });
  const Project__1 = IDL.Record({
    'id' : IDL.Int,
    'projectRepo' : IDL.Text,
    'dateCreated' : IDL.Int,
    'name' : IDL.Text,
    'creatorId' : IDL.Int,
    'lastUpdated' : IDL.Int,
    'description' : IDL.Text,
    'dfxIdentities' : IDL.Vec(IDL.Int),
    'category' : IDL.Text,
  });
  const CompleteDeploymentResponse = IDL.Record({
    'msg' : IDL.Text,
    'eventObjects' : IDL.Vec(Event__1),
    'timeStamp' : IDL.Int,
    'canisterObjects' : IDL.Vec(Canister),
    'jobObject' : Job,
    'deploymentObject' : Deployment,
    'responseStatus' : IDL.Text,
    'environmentObject' : Environment,
    'workerObject' : Worker__1,
    'projectObject' : Project__1,
  });
  const Identity = IDL.Record({
    'id' : IDL.Int,
    'principal' : IDL.Text,
    'dateCreated' : IDL.Int,
    'name' : IDL.Text,
    'creatorId' : IDL.Int,
    'lastUpdated' : IDL.Int,
    'profileWalletId' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'identityPem' : IDL.Text,
  });
  const CompleteEnvironmentResponse = IDL.Record({
    'msg' : IDL.Text,
    'latestDeploymentObject' : Deployment,
    'timeStamp' : IDL.Int,
    'canisterProfiles' : IDL.Vec(Canister),
    'responseStatus' : IDL.Text,
    'environmentObject' : Environment,
    'workerObject' : Worker__1,
    'projectObject' : Project__1,
    'identityObject' : Identity,
  });
  const CompleteIdentityResponse = IDL.Record({
    'msg' : IDL.Text,
    'timeStamp' : IDL.Int,
    'environmentObjects' : IDL.Vec(Environment),
    'responseStatus' : IDL.Text,
    'identityObject' : Identity,
  });
  const CompleteJobResponse = IDL.Record({
    'msg' : IDL.Text,
    'timeStamp' : IDL.Int,
    'jobObject' : Job,
    'responseStatus' : IDL.Text,
  });
  const CompleteProjectResponse = IDL.Record({
    'msg' : IDL.Text,
    'timeStamp' : IDL.Int,
    'environmentObjects' : IDL.Vec(Environment),
    'responseStatus' : IDL.Text,
    'projectObject' : Project__1,
  });
  const CompleteWorkerResponse = IDL.Record({
    'msg' : IDL.Text,
    'latestDeploymentObject' : Deployment,
    'latestJobObject' : Job,
    'timeStamp' : IDL.Int,
    'responseStatus' : IDL.Text,
    'environmentObject' : Environment,
    'workerObject' : Worker__1,
    'projectObject' : Project__1,
  });
  const User__1 = IDL.Record({
    'id' : IDL.Int,
    'internetId' : IDL.Text,
    'hashPass' : IDL.Text,
    'active' : IDL.Bool,
    'cellPhone' : IDL.Text,
    'dateCreated' : IDL.Int,
    'name' : IDL.Text,
    'creatorId' : IDL.Int,
    'lastUpdated' : IDL.Int,
    'email' : IDL.Text,
    'apiToken' : IDL.Text,
  });
  const DownloadAllConfigResponse = IDL.Record({
    'msg' : IDL.Text,
    'projects' : IDL.Vec(Project__1),
    'timeStamp' : IDL.Int,
    'canisterProfiles' : IDL.Vec(Canister),
    'responseStatus' : IDL.Text,
    'users' : IDL.Vec(User__1),
    'identities' : IDL.Vec(Identity),
    'environments' : IDL.Vec(Environment),
  });
  const DownloadAllLogResponse = IDL.Record({
    'msg' : IDL.Text,
    'deployments' : IDL.Vec(Deployment),
    'timeStamp' : IDL.Int,
    'jobs' : IDL.Vec(Job),
    'responseStatus' : IDL.Text,
    'events' : IDL.Vec(Event__1),
    'canisters' : IDL.Vec(Canister),
  });
  const Canister__1 = IDL.Record({
    'id' : IDL.Int,
    'canisterName' : IDL.Text,
    'canisterType' : IDL.Text,
    'canisterNetwork' : IDL.Text,
    'dateCreated' : IDL.Int,
    'name' : IDL.Text,
    'dfxJson' : IDL.Text,
    'creatorId' : IDL.Int,
    'lastUpdated' : IDL.Int,
    'description' : IDL.Text,
    'lastDeploymentId' : IDL.Int,
    'projectId' : IDL.Int,
    'environmentId' : IDL.Int,
    'category' : IDL.Text,
    'identityId' : IDL.Int,
    'canisterId' : IDL.Text,
  });
  const Deployment__1 = IDL.Record({
    'id' : IDL.Int,
    'status' : IDL.Text,
    'projectRepo' : IDL.Text,
    'executeStartTime' : IDL.Int,
    'dateCreated' : IDL.Int,
    'creatorId' : IDL.Int,
    'lastUpdated' : IDL.Int,
    'executeFinishTime' : IDL.Int,
    'projectId' : IDL.Int,
    'environmentId' : IDL.Int,
    'projectRepoBranch' : IDL.Text,
    'identityId' : IDL.Int,
    'deploymentNotes' : IDL.Text,
  });
  const Event = IDL.Record({
    'id' : IDL.Int,
    'localTime' : IDL.Int,
    'workerId' : IDL.Int,
    'deploymentId' : IDL.Int,
    'dateCreated' : IDL.Int,
    'creatorId' : IDL.Int,
    'jobId' : IDL.Int,
    'lastUpdated' : IDL.Int,
    'mainRefType' : IDL.Text,
    'projectId' : IDL.Int,
    'environmentId' : IDL.Int,
    'eventText' : IDL.Text,
    'eventType' : IDL.Text,
  });
  const Identity__1 = IDL.Record({
    'id' : IDL.Int,
    'principal' : IDL.Text,
    'dateCreated' : IDL.Int,
    'name' : IDL.Text,
    'creatorId' : IDL.Int,
    'lastUpdated' : IDL.Int,
    'profileWalletId' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'identityPem' : IDL.Text,
  });
  const Job__1 = IDL.Record({
    'id' : IDL.Int,
    'status' : IDL.Text,
    'workerId' : IDL.Int,
    'dateCreated' : IDL.Int,
    'jobType' : IDL.Text,
    'lastUpdated' : IDL.Int,
    'environmentId' : IDL.Int,
    'refType' : IDL.Text,
    'refId' : IDL.Int,
  });
  const Project = IDL.Record({
    'id' : IDL.Int,
    'projectRepo' : IDL.Text,
    'dateCreated' : IDL.Int,
    'name' : IDL.Text,
    'creatorId' : IDL.Int,
    'lastUpdated' : IDL.Int,
    'description' : IDL.Text,
    'dfxIdentities' : IDL.Vec(IDL.Int),
    'category' : IDL.Text,
  });
  const User = IDL.Record({
    'id' : IDL.Int,
    'internetId' : IDL.Text,
    'hashPass' : IDL.Text,
    'active' : IDL.Bool,
    'cellPhone' : IDL.Text,
    'dateCreated' : IDL.Int,
    'name' : IDL.Text,
    'creatorId' : IDL.Int,
    'lastUpdated' : IDL.Int,
    'email' : IDL.Text,
    'apiToken' : IDL.Text,
  });
  const Worker = IDL.Record({
    'id' : IDL.Int,
    'status' : IDL.Text,
    'privateIp' : IDL.Text,
    'dateCreated' : IDL.Int,
    'iiEnabled' : IDL.Text,
    'name' : IDL.Text,
    'creatorId' : IDL.Int,
    'ttydHttpsEnabled' : IDL.Text,
    'lastUpdated' : IDL.Int,
    'uniqueId' : IDL.Text,
    'description' : IDL.Text,
    'lastTouch' : IDL.Int,
    'lastDeploymentId' : IDL.Int,
    'dnsName' : IDL.Text,
    'publicIp' : IDL.Text,
    'category' : IDL.Text,
    'ttydHttpsCount' : IDL.Int,
    'dfxReplicaType' : IDL.Text,
  });
  const ManageCanisterResponse = IDL.Record({
    'msg' : IDL.Text,
    'canisterObject' : Canister,
    'timeStamp' : IDL.Int,
    'responseStatus' : IDL.Text,
  });
  const ManageEnvironmentResponse = IDL.Record({
    'msg' : IDL.Text,
    'timeStamp' : IDL.Int,
    'responseStatus' : IDL.Text,
    'environmentObject' : Environment,
  });
  const ManageIdentityResponse = IDL.Record({
    'msg' : IDL.Text,
    'timeStamp' : IDL.Int,
    'responseStatus' : IDL.Text,
    'identityObject' : Identity,
  });
  const ManagePrincipalResponse = IDL.Record({
    'msg' : IDL.Text,
    'timeStamp' : IDL.Int,
    'listOfManagerPrincipals' : IDL.Vec(IDL.Principal),
    'responseStatus' : IDL.Text,
  });
  const TtydHttpsEnableDisableResponse = IDL.Record({
    'msg' : IDL.Text,
    'timeStamp' : IDL.Int,
    'jobObject' : Job,
    'responseStatus' : IDL.Text,
  });
  const UplinkResponse = IDL.Record({
    'msg' : IDL.Text,
    'timeStamp' : IDL.Int,
    'canisterProfiles' : IDL.Vec(Canister),
    'jobObject' : Job,
    'deploymentObject' : Deployment,
    'responseStatus' : IDL.Text,
    'environmentObject' : Environment,
    'workerObject' : Worker__1,
    'identityObject' : Identity,
  });
  return IDL.Service({
    'addManagerPrincipalMain' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Principal],
        [LoginResponse],
        [],
      ),
    'authenticateMain' : IDL.Func(
        [LoginAttempt, IDL.Text],
        [LoginResponse],
        [],
      ),
    'checkPrincipalMain' : IDL.Func([], [IDL.Int], ['query']),
    'createDeploymentMain' : IDL.Func(
        [IDL.Text, Environment__1],
        [CreateDeploymentResponse],
        [],
      ),
    'createIiEnableJob' : IDL.Func(
        [IDL.Text, IDL.Int],
        [CreateIiEnableJobResponse],
        [],
      ),
    'getCanisterStatus' : IDL.Func([], [CanisterStatusResponse], ['query']),
    'getCompleteCanisterMain' : IDL.Func(
        [IDL.Text, IDL.Int],
        [CompleteCanisterResponse],
        ['query'],
      ),
    'getCompleteDashboardStats' : IDL.Func(
        [IDL.Text],
        [CompleteDashboardStats],
        ['query'],
      ),
    'getCompleteDeploymentMain' : IDL.Func(
        [IDL.Text, IDL.Int],
        [CompleteDeploymentResponse],
        ['query'],
      ),
    'getCompleteEnvironmentMain' : IDL.Func(
        [IDL.Text, IDL.Int],
        [CompleteEnvironmentResponse],
        ['query'],
      ),
    'getCompleteIdentityMain' : IDL.Func(
        [IDL.Text, IDL.Int],
        [CompleteIdentityResponse],
        ['query'],
      ),
    'getCompleteJobMain' : IDL.Func(
        [IDL.Text, IDL.Int],
        [CompleteJobResponse],
        ['query'],
      ),
    'getCompleteProjectMain' : IDL.Func(
        [IDL.Text, IDL.Int],
        [CompleteProjectResponse],
        ['query'],
      ),
    'getCompleteWorkerMain' : IDL.Func(
        [IDL.Text, IDL.Int],
        [CompleteWorkerResponse],
        ['query'],
      ),
    'getICPMConfigDownload' : IDL.Func(
        [IDL.Text, IDL.Text],
        [DownloadAllConfigResponse],
        [],
      ),
    'getICPMLogDownload' : IDL.Func(
        [IDL.Text, IDL.Text],
        [DownloadAllLogResponse],
        [],
      ),
    'getListOfCanisters' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Canister__1)],
        ['query'],
      ),
    'getListOfDeployments' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Deployment__1)],
        ['query'],
      ),
    'getListOfEnvironments' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Environment__1)],
        ['query'],
      ),
    'getListOfEvents' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Event)],
        ['query'],
      ),
    'getListOfIdentities' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Identity__1)],
        ['query'],
      ),
    'getListOfJobs' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Job__1)],
        ['query'],
      ),
    'getListOfProjects' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Project)],
        ['query'],
      ),
    'getListOfUsers' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(User)],
        ['query'],
      ),
    'getListOfWorkers' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Worker)],
        ['query'],
      ),
    'manageCanisterMain' : IDL.Func(
        [IDL.Text, Canister__1],
        [ManageCanisterResponse],
        [],
      ),
    'manageDeploymentMain' : IDL.Func(
        [IDL.Text, Deployment__1],
        [IDL.Text],
        [],
      ),
    'manageEnvironmentMain' : IDL.Func(
        [IDL.Text, Environment__1],
        [ManageEnvironmentResponse],
        [],
      ),
    'manageEventMain' : IDL.Func([IDL.Text, Event], [IDL.Text], []),
    'manageIdentityMain' : IDL.Func(
        [IDL.Text, Identity__1],
        [ManageIdentityResponse],
        [],
      ),
    'manageJobMain' : IDL.Func([IDL.Text, Job__1], [IDL.Text], []),
    'managePrincipalsMain' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [ManagePrincipalResponse],
        [],
      ),
    'manageProjectMain' : IDL.Func(
        [IDL.Text, Project],
        [CompleteProjectResponse],
        [],
      ),
    'manageUserMain' : IDL.Func([IDL.Text, User], [IDL.Text], []),
    'manageWorkerMain' : IDL.Func([IDL.Text, Worker], [IDL.Text], []),
    'ttydHttpsEnableDisable' : IDL.Func(
        [IDL.Text, IDL.Int],
        [TtydHttpsEnableDisableResponse],
        [],
      ),
    'workerUplink' : IDL.Func([IDL.Text, Worker], [UplinkResponse], []),
  });
};
export const init = ({ IDL }) => { return []; };
